version: '3'
services:
  shard1:
    restart: always
    image: mongo:3.6
    hostname: shard1
    command: mongod --shardsvr --replSet shard1 --port 27017 --bind_ip_all
    expose:
      - "27017"
    volumes:
       - ./scripts:/scripts
    entrypoint: /scripts/shard.sh
    networks:
      - default

  shard2:
    restart: always
    image: mongo:3.6
    hostname: shard2
    command: mongod --shardsvr --replSet shard2 --port 27017 --bind_ip_all
    expose:
      - "27017"
    volumes:
       - ./scripts:/scripts
    entrypoint: /scripts/shard.sh
    networks:
      - default

  mongocfg:
    image: mongo:3.6
    restart: always
    hostname: mongocfg
    command: mongod --configsvr --port 27019 --replSet cfg --bind_ip_all
    expose:
      - "27019"
    entrypoint: /scripts/mongocfg.sh
    volumes:
      - ./scripts:/scripts
    networks:
      - default

  database:
    image: mongo:3.6
    restart: always
    hostname: database
    command: mongos --configdb cfg/mongocfg:27019 --port 27017 --bind_ip_all
    ports:
      - "27017:27017"
    entrypoint: /scripts/mongos.sh
    volumes:
      - ./scripts:/scripts
    networks:
      - default

networks:
  default:
