version: '3'
services:
  shard1:
    image: mongo:3.6
    hostname: shard1
    command: mongod --shardsvr --replSet shard1 --port 27017 --bind_ip_all
    expose:
      - "27017"
    #entrypoint: /scripts/shard.sh
    volumes:
       - .:/scripts

  shard2:
    image: mongo:3.6
    hostname: shard2
    command: mongod --shardsvr --replSet shard2 --port 27017 --bind_ip_all
    expose:
      - "27017"
    entrypoint: /scripts/shard.sh
    volumes:
      - ./scripts:/scripts

  mongocfg:
    image: mongo:3.6
    restart: always
    hostname: mongocfg
    command: mongod --configsvr --port 27019 --replSet cfg --bind_ip_all
    expose:
      - "27019"
    entrypoint: /scripts/mongocfg.sh
    links:
      - shard1
      - shard2
    volumes:
      - ./scripts:/scripts

  database:
    image: mongo:3.6
    restart: always
    command: mongos --configdb cfg/mongocfg:27019 --port 27017 --bind_ip_all
    ports:
      - "27017:27017"
    links:
      - mongocfg
    entrypoint: /scripts/mongos.sh


#volumes:
#    - ./scripts:/scripts
