- hosts: client
  become: yes

  tasks:

    # Configuration de l'agent mongodb
    - name: "Changement de l'url"
      replace:
        dest: /apps/mongodb/mms-automation-agent/conf/mms-automation-agent.conf
        regexp: '^mmsBaseUrl=(.*)$'
        replace: "mmsBaseUrl=https://mongodb-mms.prod.svc.darva.prive"

    - name: "ajout du certificat"
      lineinfile:
        name: /apps/mongodb/mms-automation-agent/conf/mms-automation-agent.conf
        line: "sslTrustedMMSServerCertificate=/apps/mongodb/mms-automation-agent/conf/prod-svc-darva-prive-chain.pem"

    # copie de l'AC Darva
    - name: Ansible copy file to remote server
      copy:
        src: ./prod-svc-darva-prive-chain.pem
        dest: /apps/mongodb/mms-automation-agent/conf/prod-svc-darva-prive-chain.pem
        owner: mongodb
        group: mongodb

    # Arret du processus automation agent
    - name: Get process
      shell: "ps -fu mongodb|grep mongodb-mms-automation| awk '{print $2}'"
      register: _process

    - name: Kill running processes
      shell: "kill -9 {{ item }}"
      with_items: "{{ _process.stdout_lines }}"

    - name: waiting end of process 
      wait_for:
        path: "/proc/{{ item }}/status"
        state: absent
      ignore_errors: yes
      register: killed_process
      with_items: "{{ _process.stdout_lines }}"

    # Configuration systemd
    - name: "Changement version agent"
      replace:
        dest: /usr/lib/systemd/system/mongodb-mms-automation-agent.service
        regexp: '^ExecStart=(.*)$'
        replace: "ExecStart=/apps/mongodb/mms-automation-agent/bin/mongodb-mms-automation-agent-10.2.20.5992 -f /apps/mongodb/mms-automation-agent/conf/mms-automation-agent.conf"

    - name: prise en compte maj service
      shell: "systemctl daemon-reload"

    # Demarrage de l'agent
    - name: "Demarrage du service"
      service:
        name: mongodb-mms-automation-agent 
        state: started
